version: '3.8'
services:
  dev-databases:
    image: postgres:15.0
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hihi
      - POSTGRES_DB=testdb
    networks:
      - nestjs-network
##DB for test
  test-databases:
    image: postgres:15.0
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hihi
      - POSTGRES_DB=testdb
    networks:
      - nestjs-network
networks:
  nestjs-network: